POST http://localhost:5000/proprietario/ HTTP/1.1
Content-Type: application/json

{
    "cpf": "00000000014",
    "nome": "Luis Felipe",
    "telefone": "99999-6969"
}

###
POST http://localhost:5000/tipoveiculo/ HTTP/1.1
Content-Type: application/json

{
    "descricao_tipo": "Super Luxo"
}

###
POST http://localhost:5000/veiculo/ HTTP/1.1
Content-Type: application/json

{
    "placa_veiculo": "000-0000",
    "preco_veiculo": 69000,
    "proprietario": 1
}

###

PUT http://localhost:5000/produto/6 HTTP/1.1
Content-Type: application/json

{
    "nome_produto": "Lima",
    "preco_produto": 15.99
}

###

DELETE http://localhost:5000/produto/8 HTTP/1.1
Content-Type: application/json
###